# Generated by Django 3.1.4 on 2021-03-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileuload',
            name='name',
        ),
        migrations.RemoveField(
            model_name='fileuload',
            name='url',
        ),
        migrations.AddField(
            model_name='fileuload',
            name='filename',
            field=models.CharField(default=0, max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileuload',
            name='md5_hash',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
