# Generated by Django 3.1.4 on 2021-03-23 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20210322_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuload',
            name='is_original',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fileuload',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.fileuload'),
        ),
    ]
