# Generated by Django 3.1.4 on 2021-03-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20210323_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileuload',
            name='md5_hash',
            field=models.CharField(max_length=64),
        ),
    ]
