# Generated by Django 3.1.4 on 2021-03-31 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20210330_1735'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileUload',
            new_name='FileUpload',
        ),
        migrations.AlterModelTable(
            name='fileupload',
            table='apps_fileupload',
        ),
    ]
