# Generated by Django 3.1.4 on 2021-04-03 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_ocrupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocrupload',
            name='extension',
        ),
    ]
