# Generated by Django 3.1.4 on 2021-04-06 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_remove_ocrupload_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrupload',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.ocrupload'),
        ),
    ]
