# Generated by Django 3.1.4 on 2021-08-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_auto_20210406_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='filename',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='md5_hash',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ocrupload',
            name='filename',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ocrupload',
            name='md5_hash',
            field=models.CharField(max_length=100),
        ),
    ]
